#!/bin/sh

if ! hash apm 2>/dev/null; then
  echo "apm not installed, install shell additions from atom"
  exit 1
fi

echo "Restoring atom packages from ~/.atom/packages.txt"

apm install --packages-file ~/.atom/packages.txt
