brew "fish"
brew "ripgrep"
brew "asdf"
brew "helix", args: ["HEAD"]
brew "coreutils"
brew "jq"
brew "bat"
brew "lazygit"
brew "yazi"
brew "fzf"
brew "zoxide"
brew "fd"
brew "scooter"
brew "just"

cask "font-fira-code"
cask "font-iosevka"
cask "font-iosevka-etoile"
cask "font-jetbrains-mono"
