#!/bin/sh

# Bootstrap file

system_type=$(uname -s)

# Only for macOS
if [ "$system_type" = "Darwin" ]; then
  if [ -d "$HOME/.iterm2" ]; then
    if [ ! -f "$HOME/.iterm2/wp.jpg" ]; then
      echo "Downloading anime wallpaper"
      curl https://static.zerochan.net/Konoe.full.1709831.jpg --output $HOME/.iterm2/wp.jpg
    fi

    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "~/.iterm2"
    defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder 1
    echo
  fi

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    echo
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
    echo
  fi
fi

# Only for Linux
if [ "$system_type" = "Linux" ]; then
  # Link vscode config to the same folder as on mac
  rm "$HOME/.config/Code - OSS/User/settings.json"
  rm "$HOME/.config/Code/User/settings.json"
  ln "$HOME/Library/Application Support/Code/User/settings.json" "$HOME/.config/Code - OSS/User/settings.json"
  ln "$HOME/Library/Application Support/Code/User/settings.json" "$HOME/.config/Code/User/settings.json"
fi

# Install antigen at .antigen/antigen.zsh
if [ ! -f "$HOME/.antigen/antigen.zsh" ]; then
  echo "Installing antigen"

  mkdir -p $HOME/.antigen
  curl -L git.io/antigen > $HOME/.antigen/antigen.zsh
  echo
fi

echo "Restoring vscode packages"

if ! hash code 2>/dev/null; then
  echo "[!] code command not installed, install shell additions from vscode"
else
  bash ~/.dotbin/dotbin-vscode-restore-packages
  echo
fi

if [ ! -d "$HOME/.vim/bundle/Vundle.vim" ]; then
  echo "Installing Vundle"
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  echo
fi

echo "Installing Vundle plugins"
vim +PluginInstall +qall
echo

echo "[!] Restart terminal for changes to take effect"

if [ "$system_type" = "Darwin" ]; then
  echo "[!] Then run this: compaudit | xargs chmod g-w"
fi
