#!/bin/sh

# Bootstrap file

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "~/.iterm2"
    defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder 1
  fi
fi

# Install antigen at .antigen/antigen.zsh
if [ ! -f "$HOME/.antigen/antigen.zsh" ]; then
  echo "Installing antigen"

  mkdir -p $HOME/.antigen
  curl -L git.io/antigen > $HOME/.antigen/antigen.zsh
fi

echo "Restoring atom packages"

if ! hash apm 2>/dev/null; then
  echo "[!] apm not installed, install shell additions from atom"
else
  bash ~/.dotbin/dotbin-atom-restore-packages
fi

echo
echo "[!] Restart terminal for changes to take effect"
