#!/bin/sh

# Bootstrap file

system_type=$(uname -s)

# Only for macOS
if [ "$system_type" = "Darwin" ]; then
  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
    echo
  fi
fi

echo "Launching fish boostrap"
fish $HOME/.config/yadm/bootstrap.fish

echo "[!] Change your shell to fish now and restart the terminal"
