theme = "base16_lynx"

[editor]
line-number = "relative"
mouse = false
insert-final-newline = true
bufferline = "multiple"
true-color = true
color-modes = true

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
newline = "none"

[editor.soft-wrap]
enable = true

# Disable arrows for insert mode
[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.normal]
# Disable arrows for normal mode
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

# Subword navigation
A-w = "move_next_sub_word_start"
A-b = "move_prev_sub_word_end"

[keys.select]
# Subword navigation
A-w = "extend_next_sub_word_start"
A-b = "extend_prev_sub_word_end"
