theme = "base16_lynx"

[editor]
line-number = "relative"
mouse = false
insert-final-newline = true
bufferline = "multiple"
true-color = true
color-modes = true

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
newline = "none"

[editor.soft-wrap]
enable = true

# Disable arrows for insert mode
[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

# Disable arrows for normal mode
[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
