[language-server.rubocop]
command = "bundle"
args = ["exec", "rubocop", "--lsp"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "ruby"
auto-format = true
language-servers = ["ruby-lsp", "solargraph", "rubocop"]

[[language]]
name = "markdown"
language-servers = ["marksman", "markdown-oxide", "harper-ls"]
